name: PlayerTitles
version: '${version}'
main: dev.souofrancisco.playertitles.PlayerTitlesPlugin
api-version: '1.21'
description: '${description}'
author: souofrancisco
depend: [CommandAPI]
softdepend: [PlaceholderAPI]
folia-supported: true
